### PR TITLE
Support `antigen bundle`

### PR DESCRIPTION
**Pull request by himanoa**
Enable loading of this plugin from Antigen.

## References

https://github.com/olets/zsh-abbr/blob/main/zsh-abbr.plugin.zsh

### CODE REVIEW

**Comment by azu** [comment]
Can you add this usage to README?

**Comment by himanoa** [comment]
OK.

**Comment by himanoa** [comment]
OK.

**Comment by himanoa** [comment]
Sorry for the late response.

Updated installation document.

**Comment by azu** [comment]
Thanks!

**Pull request merged**
